import {Category} from '../models/category.model';
import {ROOT_CATEGORY_ID} from './root-category-id.constant';

export const SEED_CATEGORIES: Category[] = [
  {
    id: ROOT_CATEGORY_ID,
    name: 'unknown',
    displayName: 'Otros',
    icon: 'folder-open',
    color: '#6B7280',
    applyType: 'BOTH',
    isRoot: true,
  },
  {
    id: 'payroll',
    name: 'payroll',
    displayName: 'Nómina',
    icon: 'banknote',
    color: '#10B981',
    applyType: 'INCOME',
  },
  {
    id: 'services',
    name: 'services',
    displayName: 'Servicios',
    icon: 'zap',
    color: '#F59E0B',
    applyType: 'EXPENSE',
  },
  {
    id: 'car',
    name: 'car',
    displayName: 'Auto',
    icon: 'car',
    color: '#3B82F6',
    applyType: 'EXPENSE',
  },
  {
    id: 'kids',
    name: 'kids',
    displayName: 'Hijos',
    icon: 'baby',
    color: '#EC4899',
    applyType: 'EXPENSE',
  },
  {
    id: 'debts',
    name: 'debts',
    displayName: 'Deudas',
    icon: 'credit-card',
    color: '#EF4444',
    applyType: 'EXPENSE',
  },
  {
    id: 'gifts',
    name: 'gifts',
    displayName: 'Regalos',
    icon: 'gift',
    color: '#8B5CF6',
    applyType: 'BOTH',
  },
  {
    id: 'donations',
    name: 'donations',
    displayName: 'Donaciones',
    icon: 'heart-handshake',
    color: '#14B8A6',
    applyType: 'BOTH',
  },
  {
    id: 'transfer',
    name: 'transfer',
    displayName: 'Transferencia',
    icon: 'arrow-left-right',
    color: '#6366F1',
    applyType: 'TRANSFER',
    isSystem: true,
  },
  {
    id: 'adjustment',
    name: 'adjustment',
    displayName: 'Ajuste de Saldo',
    icon: 'scale',
    color: '#64748B',
    applyType: 'BOTH',
    isSystem: true,
  },
];
